// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BriefStatistics is the golang structure of table tt_brief_statistics for DAO operations like Where/Data.
type BriefStatistics struct {
	g.Meta       `orm:"table:tt_brief_statistics, do:true"`
	Id           interface{} // 主键
	Time         *gtime.Time // 日期
	PodCount     interface{} // 当日的pod总数
	NodeCount    interface{} //
	ClusterCount interface{} //
	ServiceCount interface{} //
}
