// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EventRecord is the golang structure of table tt_event_record for DAO operations like Where/Data.
type EventRecord struct {
	g.Meta      `orm:"table:tt_event_record, do:true"`
	Id          interface{} //
	Subject     interface{} // 标题
	Version     interface{} // 版本
	Eid         interface{} // event id
	Source      interface{} // 事件源
	Type        interface{} // 事件类型
	Time        *gtime.Time // 触发时间
	ContentType interface{} // 内容类型
	Data        interface{} // 数据参数
	IsRespond   interface{} // 是否有响应函数
	Resp        interface{} // 响应数据(暂时不记录)
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
	DeletedAt   *gtime.Time //
}
