// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// K8SClusterConfig is the golang structure of table tt_k8s_cluster_config for DAO operations like Where/Data.
type K8SClusterConfig struct {
	g.Meta     `orm:"table:tt_k8s_cluster_config, do:true"`
	Id         interface{} //
	Uuid       interface{} //
	Name       interface{} //
	ApiServer  interface{} //
	Cloud      interface{} // 云商
	CloudId    interface{} // 云商ID
	IsReady    interface{} // kubeconfig是否可用
	RegionId   interface{} //
	IsSync     interface{} // 是否从cmdb同步回来的
	Kubeconfig interface{} //
	Desc       interface{} //
	CreatedAt  *gtime.Time //
	UpdatedAt  *gtime.Time //
	DeletedAt  *gtime.Time //
}
