// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// K8SDeployment is the golang structure of table tt_k8s_deployment for DAO operations like Where/Data.
type K8SDeployment struct {
	g.Meta        `orm:"table:tt_k8s_deployment, do:true"`
	Uuid          interface{} // deploy 真实的uid
	Cluster       interface{} // cluster name
	ClusterId     interface{} // tt_k8s_cluster_config id
	Namespace     interface{} // namespace name
	Deployment    interface{} // deploy name
	ApiServer     interface{} // k8s server
	Replicas      interface{} //
	AvailReplicas interface{} //
	Age           interface{} //
	Images        interface{} //
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
	DeletedAt     *gtime.Time //
}
