// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// OpRecord is the golang structure of table tt_op_record for DAO operations like Where/Data.
type OpRecord struct {
	g.Meta      `orm:"table:tt_op_record, do:true"`
	Id          interface{} //
	Username    interface{} //
	Uri         interface{} //
	Method      interface{} //
	Code        interface{} //
	Header      interface{} //
	QueryParams interface{} //
	QueryBody   interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
	DeletedAt   *gtime.Time //
}
