// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PrAuthK8SAuth is the golang structure of table tt_pr_auth_k8s_auth for DAO operations like Where/Data.
type PrAuthK8SAuth struct {
	g.Meta       `orm:"table:tt_pr_auth_k8s_auth, do:true"`
	Id           interface{} //
	AuthName     interface{} // 权限名, 如:svc-r, deploy-{name}-r
	Authority    interface{} // R | W | X
	Kind         interface{} // 资源种类
	ClusterId    interface{} //
	ClusterName  interface{} //
	Namespace    interface{} //
	Desc         interface{} // 描述
	ResourceName interface{} // Resource Name
}
