// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PrAuthRoleViewerRelated is the golang structure of table tt_pr_auth_role_viewer_related for DAO operations like Where/Data.
type PrAuthRoleViewerRelated struct {
	g.Meta   `orm:"table:tt_pr_auth_role_viewer_related, do:true"`
	Id       interface{} //
	RoleId   interface{} //
	ViewerId interface{} //
}
