// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PrAuthRoleK8SRelated is the golang structure of table tt_pr_auth_role_k8s_related for DAO operations like Where/Data.
type PrAuthRoleK8SRelated struct {
	g.Meta `orm:"table:tt_pr_auth_role_k8s_related, do:true"`
	Id     interface{} //
	RoleId interface{} //
	K8SId  interface{} //
}
