// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PrAuthRole is the golang structure of table tt_pr_auth_role for DAO operations like Where/Data.
type PrAuthRole struct {
	g.Meta    `orm:"table:tt_pr_auth_role, do:true"`
	Id        interface{} //
	RoleName  interface{} // role name
	Desc      interface{} //
	Kind      interface{} // 权限种类(viewer, k8s)
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	DeletedAt *gtime.Time //
}
