// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PrAuthRoleUserRelated is the golang structure of table tt_pr_auth_role_user_related for DAO operations like Where/Data.
type PrAuthRoleUserRelated struct {
	g.Meta `orm:"table:tt_pr_auth_role_user_related, do:true"`
	Id     interface{} //
	RoleId interface{} //
	UserId interface{} //
}
