// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table tt_user for DAO operations like Where/Data.
type User struct {
	g.Meta         `orm:"table:tt_user, do:true"`
	Id             interface{} //
	Username       interface{} // username
	NickName       interface{} //
	Password       interface{} // password
	Gender         interface{} // gender
	IsActive       interface{} // 是否激活
	IsAdmin        interface{} // 是否admin
	IsClusterAdmin interface{} // 是否有权限管理所有集群
	Namespaces     interface{} // 授权namespace
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
	DeletedAt      *gtime.Time //
	Uuid           interface{} // SSO uid
	Desc           interface{} // 描述
	Email          interface{} //
	FeishuId       interface{} // 飞书系统的openId
}
