// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// OpenapiTokenDao is the data access object for table tt_openapi_token.
type OpenapiTokenDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns OpenapiTokenColumns // columns contains all the column names of Table for convenient usage.
}

// OpenapiTokenColumns defines and stores column names for table tt_openapi_token.
type OpenapiTokenColumns struct {
	Id        string //
	Name      string // 唯一标识
	Token     string // token
	Desc      string // 描述
	CreatedAt string //
	UpdatedAt string //
	DeletedAt string //
}

// openapiTokenColumns holds the columns for table tt_openapi_token.
var openapiTokenColumns = OpenapiTokenColumns{
	Id:        "id",
	Name:      "name",
	Token:     "token",
	Desc:      "desc",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}

// NewOpenapiTokenDao creates and returns a new DAO object for table data access.
func NewOpenapiTokenDao() *OpenapiTokenDao {
	return &OpenapiTokenDao{
		group:   "default",
		table:   "tt_openapi_token",
		columns: openapiTokenColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *OpenapiTokenDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *OpenapiTokenDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *OpenapiTokenDao) Columns() OpenapiTokenColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *OpenapiTokenDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *OpenapiTokenDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *OpenapiTokenDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
