// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PrAuthK8SAuthDao is the data access object for table tt_pr_auth_k8s_auth.
type PrAuthK8SAuthDao struct {
	table   string               // table is the underlying table name of the DAO.
	group   string               // group is the database configuration group name of current DAO.
	columns PrAuthK8SAuthColumns // columns contains all the column names of Table for convenient usage.
}

// PrAuthK8SAuthColumns defines and stores column names for table tt_pr_auth_k8s_auth.
type PrAuthK8SAuthColumns struct {
	Id           string //
	AuthName     string // 权限名, 如:svc-r, deploy-{name}-r
	Authority    string // R | W | X
	Kind         string // 资源种类
	ClusterId    string //
	ClusterName  string //
	Namespace    string //
	Desc         string // 描述
	ResourceName string // Resource Name
}

// prAuthK8SAuthColumns holds the columns for table tt_pr_auth_k8s_auth.
var prAuthK8SAuthColumns = PrAuthK8SAuthColumns{
	Id:           "id",
	AuthName:     "auth_name",
	Authority:    "authority",
	Kind:         "kind",
	ClusterId:    "cluster_id",
	ClusterName:  "cluster_name",
	Namespace:    "namespace",
	Desc:         "desc",
	ResourceName: "resource_name",
}

// NewPrAuthK8SAuthDao creates and returns a new DAO object for table data access.
func NewPrAuthK8SAuthDao() *PrAuthK8SAuthDao {
	return &PrAuthK8SAuthDao{
		group:   "default",
		table:   "tt_pr_auth_k8s_auth",
		columns: prAuthK8SAuthColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PrAuthK8SAuthDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PrAuthK8SAuthDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PrAuthK8SAuthDao) Columns() PrAuthK8SAuthColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PrAuthK8SAuthDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PrAuthK8SAuthDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PrAuthK8SAuthDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
