// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PrAuthViewerAuthDao is the data access object for table tt_pr_auth_viewer_auth.
type PrAuthViewerAuthDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns PrAuthViewerAuthColumns // columns contains all the column names of Table for convenient usage.
}

// PrAuthViewerAuthColumns defines and stores column names for table tt_pr_auth_viewer_auth.
type PrAuthViewerAuthColumns struct {
	Id        string //
	AuthName  string //
	Authority string //
	Desc      string //
	Kind      string //
	Rank      string //
}

// prAuthViewerAuthColumns holds the columns for table tt_pr_auth_viewer_auth.
var prAuthViewerAuthColumns = PrAuthViewerAuthColumns{
	Id:        "id",
	AuthName:  "auth_name",
	Authority: "authority",
	Desc:      "desc",
	Kind:      "kind",
	Rank:      "rank",
}

// NewPrAuthViewerAuthDao creates and returns a new DAO object for table data access.
func NewPrAuthViewerAuthDao() *PrAuthViewerAuthDao {
	return &PrAuthViewerAuthDao{
		group:   "default",
		table:   "tt_pr_auth_viewer_auth",
		columns: prAuthViewerAuthColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PrAuthViewerAuthDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PrAuthViewerAuthDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PrAuthViewerAuthDao) Columns() PrAuthViewerAuthColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PrAuthViewerAuthDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PrAuthViewerAuthDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PrAuthViewerAuthDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
