// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PrAuthRoleK8SRelatedDao is the data access object for table tt_pr_auth_role_k8s_related.
type PrAuthRoleK8SRelatedDao struct {
	table   string                      // table is the underlying table name of the DAO.
	group   string                      // group is the database configuration group name of current DAO.
	columns PrAuthRoleK8SRelatedColumns // columns contains all the column names of Table for convenient usage.
}

// PrAuthRoleK8SRelatedColumns defines and stores column names for table tt_pr_auth_role_k8s_related.
type PrAuthRoleK8SRelatedColumns struct {
	Id     string //
	RoleId string //
	K8SId  string //
}

// prAuthRoleK8SRelatedColumns holds the columns for table tt_pr_auth_role_k8s_related.
var prAuthRoleK8SRelatedColumns = PrAuthRoleK8SRelatedColumns{
	Id:     "id",
	RoleId: "role_id",
	K8SId:  "k8s_id",
}

// NewPrAuthRoleK8SRelatedDao creates and returns a new DAO object for table data access.
func NewPrAuthRoleK8SRelatedDao() *PrAuthRoleK8SRelatedDao {
	return &PrAuthRoleK8SRelatedDao{
		group:   "default",
		table:   "tt_pr_auth_role_k8s_related",
		columns: prAuthRoleK8SRelatedColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PrAuthRoleK8SRelatedDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PrAuthRoleK8SRelatedDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PrAuthRoleK8SRelatedDao) Columns() PrAuthRoleK8SRelatedColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PrAuthRoleK8SRelatedDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PrAuthRoleK8SRelatedDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PrAuthRoleK8SRelatedDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
