// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PrAuthRoleDao is the data access object for table tt_pr_auth_role.
type PrAuthRoleDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns PrAuthRoleColumns // columns contains all the column names of Table for convenient usage.
}

// PrAuthRoleColumns defines and stores column names for table tt_pr_auth_role.
type PrAuthRoleColumns struct {
	Id        string //
	RoleName  string // role name
	Desc      string //
	Kind      string // 权限种类(viewer, k8s)
	CreatedAt string //
	UpdatedAt string //
	DeletedAt string //
}

// prAuthRoleColumns holds the columns for table tt_pr_auth_role.
var prAuthRoleColumns = PrAuthRoleColumns{
	Id:        "id",
	RoleName:  "role_name",
	Desc:      "desc",
	Kind:      "kind",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}

// NewPrAuthRoleDao creates and returns a new DAO object for table data access.
func NewPrAuthRoleDao() *PrAuthRoleDao {
	return &PrAuthRoleDao{
		group:   "default",
		table:   "tt_pr_auth_role",
		columns: prAuthRoleColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PrAuthRoleDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PrAuthRoleDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PrAuthRoleDao) Columns() PrAuthRoleColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PrAuthRoleDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PrAuthRoleDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PrAuthRoleDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
