// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PrAuthRoleUserRelatedDao is the data access object for table tt_pr_auth_role_user_related.
type PrAuthRoleUserRelatedDao struct {
	table   string                       // table is the underlying table name of the DAO.
	group   string                       // group is the database configuration group name of current DAO.
	columns PrAuthRoleUserRelatedColumns // columns contains all the column names of Table for convenient usage.
}

// PrAuthRoleUserRelatedColumns defines and stores column names for table tt_pr_auth_role_user_related.
type PrAuthRoleUserRelatedColumns struct {
	Id     string //
	RoleId string //
	UserId string //
}

// prAuthRoleUserRelatedColumns holds the columns for table tt_pr_auth_role_user_related.
var prAuthRoleUserRelatedColumns = PrAuthRoleUserRelatedColumns{
	Id:     "id",
	RoleId: "role_id",
	UserId: "user_id",
}

// NewPrAuthRoleUserRelatedDao creates and returns a new DAO object for table data access.
func NewPrAuthRoleUserRelatedDao() *PrAuthRoleUserRelatedDao {
	return &PrAuthRoleUserRelatedDao{
		group:   "default",
		table:   "tt_pr_auth_role_user_related",
		columns: prAuthRoleUserRelatedColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PrAuthRoleUserRelatedDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PrAuthRoleUserRelatedDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PrAuthRoleUserRelatedDao) Columns() PrAuthRoleUserRelatedColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PrAuthRoleUserRelatedDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PrAuthRoleUserRelatedDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PrAuthRoleUserRelatedDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
