// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PrAuthRoleViewerRelatedDao is the data access object for table tt_pr_auth_role_viewer_related.
type PrAuthRoleViewerRelatedDao struct {
	table   string                         // table is the underlying table name of the DAO.
	group   string                         // group is the database configuration group name of current DAO.
	columns PrAuthRoleViewerRelatedColumns // columns contains all the column names of Table for convenient usage.
}

// PrAuthRoleViewerRelatedColumns defines and stores column names for table tt_pr_auth_role_viewer_related.
type PrAuthRoleViewerRelatedColumns struct {
	Id       string //
	RoleId   string //
	ViewerId string //
}

// prAuthRoleViewerRelatedColumns holds the columns for table tt_pr_auth_role_viewer_related.
var prAuthRoleViewerRelatedColumns = PrAuthRoleViewerRelatedColumns{
	Id:       "id",
	RoleId:   "role_id",
	ViewerId: "viewer_id",
}

// NewPrAuthRoleViewerRelatedDao creates and returns a new DAO object for table data access.
func NewPrAuthRoleViewerRelatedDao() *PrAuthRoleViewerRelatedDao {
	return &PrAuthRoleViewerRelatedDao{
		group:   "default",
		table:   "tt_pr_auth_role_viewer_related",
		columns: prAuthRoleViewerRelatedColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PrAuthRoleViewerRelatedDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PrAuthRoleViewerRelatedDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PrAuthRoleViewerRelatedDao) Columns() PrAuthRoleViewerRelatedColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PrAuthRoleViewerRelatedDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PrAuthRoleViewerRelatedDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PrAuthRoleViewerRelatedDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
