// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserDao is the data access object for table tt_user.
type UserDao struct {
	table   string      // table is the underlying table name of the DAO.
	group   string      // group is the database configuration group name of current DAO.
	columns UserColumns // columns contains all the column names of Table for convenient usage.
}

// UserColumns defines and stores column names for table tt_user.
type UserColumns struct {
	Id             string //
	Username       string // username
	NickName       string //
	Password       string // password
	Gender         string // gender
	IsActive       string // 是否激活
	IsAdmin        string // 是否admin
	IsClusterAdmin string // 是否有权限管理所有集群
	Namespaces     string // 授权namespace
	CreatedAt      string //
	UpdatedAt      string //
	DeletedAt      string //
	Uuid           string // SSO uid
	Desc           string // 描述
	Email          string //
	FeishuId       string // 飞书系统的openId
}

// userColumns holds the columns for table tt_user.
var userColumns = UserColumns{
	Id:             "id",
	Username:       "username",
	NickName:       "nick_name",
	Password:       "password",
	Gender:         "gender",
	IsActive:       "is_active",
	IsAdmin:        "is_admin",
	IsClusterAdmin: "is_cluster_admin",
	Namespaces:     "namespaces",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
	DeletedAt:      "deleted_at",
	Uuid:           "uuid",
	Desc:           "desc",
	Email:          "email",
	FeishuId:       "feishu_id",
}

// NewUserDao creates and returns a new DAO object for table data access.
func NewUserDao() *UserDao {
	return &UserDao{
		group:   "default",
		table:   "tt_user",
		columns: userColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserDao) Columns() UserColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
