
# 工具相关配置
gfcli:
  # 工具编译配置
  build:
    name:     "tt-cloud-visual"
    arch:     "amd64"
    system:   "linux,darwin,windows"
    mod:      ""
    cgo:      0

  # dao生成
  gen:
    dao:
      - link:            "mysql:root:YUE4MTYwODA2Ny4K@tcp(139.198.18.114:6033)/tt-cloud-visual"
        removePrefix:    "tt_"
        descriptionTag:  true
        noModelComment:  true

