// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-test/internal/dao/internal"
)

// internalBriefStatisticsDao is internal type for wrapping internal DAO implements.
type internalBriefStatisticsDao = *internal.BriefStatisticsDao

// briefStatisticsDao is the data access object for table tt_brief_statistics.
// You can define custom methods on it to extend its functionality as you wish.
type briefStatisticsDao struct {
	internalBriefStatisticsDao
}

var (
	// BriefStatistics is globally public accessible object for table tt_brief_statistics operations.
	BriefStatistics = briefStatisticsDao{
		internal.NewBriefStatisticsDao(),
	}
)

// Fill with you ideas below.
