// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-test/internal/dao/internal"
)

// internalEventRecordDao is internal type for wrapping internal DAO implements.
type internalEventRecordDao = *internal.EventRecordDao

// eventRecordDao is the data access object for table tt_event_record.
// You can define custom methods on it to extend its functionality as you wish.
type eventRecordDao struct {
	internalEventRecordDao
}

var (
	// EventRecord is globally public accessible object for table tt_event_record operations.
	EventRecord = eventRecordDao{
		internal.NewEventRecordDao(),
	}
)

// Fill with you ideas below.
