// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-test/internal/dao/internal"
)

// internalK8SClusterConfigDao is internal type for wrapping internal DAO implements.
type internalK8SClusterConfigDao = *internal.K8SClusterConfigDao

// k8SClusterConfigDao is the data access object for table tt_k8s_cluster_config.
// You can define custom methods on it to extend its functionality as you wish.
type k8SClusterConfigDao struct {
	internalK8SClusterConfigDao
}

var (
	// K8SClusterConfig is globally public accessible object for table tt_k8s_cluster_config operations.
	K8SClusterConfig = k8SClusterConfigDao{
		internal.NewK8SClusterConfigDao(),
	}
)

// Fill with you ideas below.
