// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-test/internal/dao/internal"
)

// internalK8SDeploymentDao is internal type for wrapping internal DAO implements.
type internalK8SDeploymentDao = *internal.K8SDeploymentDao

// k8SDeploymentDao is the data access object for table tt_k8s_deployment.
// You can define custom methods on it to extend its functionality as you wish.
type k8SDeploymentDao struct {
	internalK8SDeploymentDao
}

var (
	// K8SDeployment is globally public accessible object for table tt_k8s_deployment operations.
	K8SDeployment = k8SDeploymentDao{
		internal.NewK8SDeploymentDao(),
	}
)

// Fill with you ideas below.
