// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-test/internal/dao/internal"
)

// internalOpRecordDao is internal type for wrapping internal DAO implements.
type internalOpRecordDao = *internal.OpRecordDao

// opRecordDao is the data access object for table tt_op_record.
// You can define custom methods on it to extend its functionality as you wish.
type opRecordDao struct {
	internalOpRecordDao
}

var (
	// OpRecord is globally public accessible object for table tt_op_record operations.
	OpRecord = opRecordDao{
		internal.NewOpRecordDao(),
	}
)

// Fill with you ideas below.
