// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-test/internal/dao/internal"
)

// internalOpenapiTokenDao is internal type for wrapping internal DAO implements.
type internalOpenapiTokenDao = *internal.OpenapiTokenDao

// openapiTokenDao is the data access object for table tt_openapi_token.
// You can define custom methods on it to extend its functionality as you wish.
type openapiTokenDao struct {
	internalOpenapiTokenDao
}

var (
	// OpenapiToken is globally public accessible object for table tt_openapi_token operations.
	OpenapiToken = openapiTokenDao{
		internal.NewOpenapiTokenDao(),
	}
)

// Fill with you ideas below.
