// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-test/internal/dao/internal"
)

// internalPrAuthViewerAuthDao is internal type for wrapping internal DAO implements.
type internalPrAuthViewerAuthDao = *internal.PrAuthViewerAuthDao

// prAuthViewerAuthDao is the data access object for table tt_pr_auth_viewer_auth.
// You can define custom methods on it to extend its functionality as you wish.
type prAuthViewerAuthDao struct {
	internalPrAuthViewerAuthDao
}

var (
	// PrAuthViewerAuth is globally public accessible object for table tt_pr_auth_viewer_auth operations.
	PrAuthViewerAuth = prAuthViewerAuthDao{
		internal.NewPrAuthViewerAuthDao(),
	}
)

// Fill with you ideas below.
