// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-test/internal/dao/internal"
)

// internalPrAuthRoleViewerRelatedDao is internal type for wrapping internal DAO implements.
type internalPrAuthRoleViewerRelatedDao = *internal.PrAuthRoleViewerRelatedDao

// prAuthRoleViewerRelatedDao is the data access object for table tt_pr_auth_role_viewer_related.
// You can define custom methods on it to extend its functionality as you wish.
type prAuthRoleViewerRelatedDao struct {
	internalPrAuthRoleViewerRelatedDao
}

var (
	// PrAuthRoleViewerRelated is globally public accessible object for table tt_pr_auth_role_viewer_related operations.
	PrAuthRoleViewerRelated = prAuthRoleViewerRelatedDao{
		internal.NewPrAuthRoleViewerRelatedDao(),
	}
)

// Fill with you ideas below.
