// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-test/internal/dao/internal"
)

// internalPrAuthRoleK8SRelatedDao is internal type for wrapping internal DAO implements.
type internalPrAuthRoleK8SRelatedDao = *internal.PrAuthRoleK8SRelatedDao

// prAuthRoleK8SRelatedDao is the data access object for table tt_pr_auth_role_k8s_related.
// You can define custom methods on it to extend its functionality as you wish.
type prAuthRoleK8SRelatedDao struct {
	internalPrAuthRoleK8SRelatedDao
}

var (
	// PrAuthRoleK8SRelated is globally public accessible object for table tt_pr_auth_role_k8s_related operations.
	PrAuthRoleK8SRelated = prAuthRoleK8SRelatedDao{
		internal.NewPrAuthRoleK8SRelatedDao(),
	}
)

// Fill with you ideas below.
