// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-test/internal/dao/internal"
)

// internalPrAuthRoleDao is internal type for wrapping internal DAO implements.
type internalPrAuthRoleDao = *internal.PrAuthRoleDao

// prAuthRoleDao is the data access object for table tt_pr_auth_role.
// You can define custom methods on it to extend its functionality as you wish.
type prAuthRoleDao struct {
	internalPrAuthRoleDao
}

var (
	// PrAuthRole is globally public accessible object for table tt_pr_auth_role operations.
	PrAuthRole = prAuthRoleDao{
		internal.NewPrAuthRoleDao(),
	}
)

// Fill with you ideas below.
