// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-test/internal/dao/internal"
)

// internalPrAuthRoleUserRelatedDao is internal type for wrapping internal DAO implements.
type internalPrAuthRoleUserRelatedDao = *internal.PrAuthRoleUserRelatedDao

// prAuthRoleUserRelatedDao is the data access object for table tt_pr_auth_role_user_related.
// You can define custom methods on it to extend its functionality as you wish.
type prAuthRoleUserRelatedDao struct {
	internalPrAuthRoleUserRelatedDao
}

var (
	// PrAuthRoleUserRelated is globally public accessible object for table tt_pr_auth_role_user_related operations.
	PrAuthRoleUserRelated = prAuthRoleUserRelatedDao{
		internal.NewPrAuthRoleUserRelatedDao(),
	}
)

// Fill with you ideas below.
