// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// K8SClusterConfig is the golang structure for table k8s_cluster_config.
type K8SClusterConfig struct {
	Id         uint        `json:"id"         description:""`
	Uuid       string      `json:"uuid"       description:""`
	Name       string      `json:"name"       description:""`
	ApiServer  string      `json:"apiServer"  description:""`
	Cloud      string      `json:"cloud"      description:"云商"`
	CloudId    string      `json:"cloudId"    description:"云商ID"`
	IsReady    int         `json:"isReady"    description:"kubeconfig是否可用"`
	RegionId   string      `json:"regionId"   description:""`
	IsSync     int         `json:"isSync"     description:"是否从cmdb同步回来的"`
	Kubeconfig string      `json:"kubeconfig" description:""`
	Desc       string      `json:"desc"       description:""`
	CreatedAt  *gtime.Time `json:"createdAt"  description:""`
	UpdatedAt  *gtime.Time `json:"updatedAt"  description:""`
	DeletedAt  *gtime.Time `json:"deletedAt"  description:""`
}
