// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// K8SDeployment is the golang structure for table k8s_deployment.
type K8SDeployment struct {
	Uuid          string      `json:"uuid"          description:"deploy 真实的uid"`
	Cluster       string      `json:"cluster"       description:"cluster name"`
	ClusterId     int         `json:"clusterId"     description:"tt_k8s_cluster_config id"`
	Namespace     string      `json:"namespace"     description:"namespace name"`
	Deployment    string      `json:"deployment"    description:"deploy name"`
	ApiServer     string      `json:"apiServer"     description:"k8s server"`
	Replicas      int         `json:"replicas"      description:""`
	AvailReplicas int         `json:"availReplicas" description:""`
	Age           string      `json:"age"           description:""`
	Images        string      `json:"images"        description:""`
	CreatedAt     *gtime.Time `json:"createdAt"     description:""`
	UpdatedAt     *gtime.Time `json:"updatedAt"     description:""`
	DeletedAt     *gtime.Time `json:"deletedAt"     description:""`
}
