// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// OpenapiToken is the golang structure for table openapi_token.
type OpenapiToken struct {
	Id        uint        `json:"id"        description:""`
	Name      string      `json:"name"      description:"唯一标识"`
	Token     string      `json:"token"     description:"token"`
	Desc      string      `json:"desc"      description:"描述"`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
	DeletedAt *gtime.Time `json:"deletedAt" description:""`
}
