// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// PrAuthViewerAuth is the golang structure for table pr_auth_viewer_auth.
type PrAuthViewerAuth struct {
	Id        uint   `json:"id"        description:""`
	AuthName  string `json:"authName"  description:""`
	Authority string `json:"authority" description:""`
	Desc      string `json:"desc"      description:""`
	Kind      string `json:"kind"      description:""`
	Rank      int    `json:"rank"      description:""`
}
