// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// PrAuthRoleK8SRelated is the golang structure for table pr_auth_role_k8s_related.
type PrAuthRoleK8SRelated struct {
	Id     uint   `json:"id"     description:""`
	RoleId int    `json:"roleId" description:""`
	K8SId  string `json:"k8SId"  description:""`
}
