// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// PrAuthRoleUserRelated is the golang structure for table pr_auth_role_user_related.
type PrAuthRoleUserRelated struct {
	Id     uint `json:"id"     description:""`
	RoleId int  `json:"roleId" description:""`
	UserId int  `json:"userId" description:""`
}
