// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// PrAuthRoleViewerRelated is the golang structure for table pr_auth_role_viewer_related.
type PrAuthRoleViewerRelated struct {
	Id       uint `json:"id"       description:""`
	RoleId   int  `json:"roleId"   description:""`
	ViewerId int  `json:"viewerId" description:""`
}
