// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id             uint        `json:"id"             description:""`
	Username       string      `json:"username"       description:"username"`
	NickName       string      `json:"nickName"       description:""`
	Password       string      `json:"password"       description:"password"`
	Gender         string      `json:"gender"         description:"gender"`
	IsActive       int         `json:"isActive"       description:"是否激活"`
	IsAdmin        int         `json:"isAdmin"        description:"是否admin"`
	IsClusterAdmin int         `json:"isClusterAdmin" description:"是否有权限管理所有集群"`
	Namespaces     string      `json:"namespaces"     description:"授权namespace"`
	CreatedAt      *gtime.Time `json:"createdAt"      description:""`
	UpdatedAt      *gtime.Time `json:"updatedAt"      description:""`
	DeletedAt      *gtime.Time `json:"deletedAt"      description:""`
	Uuid           string      `json:"uuid"           description:"SSO uid"`
	Desc           string      `json:"desc"           description:"描述"`
	Email          string      `json:"email"          description:""`
	FeishuId       string      `json:"feishuId"       description:"飞书系统的openId"`
}
